apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rag-a1732009339035 
  description: Secure Supply Chain Example for RAG Chatbot Application   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=rag-a1732009339035  
    janus-idp.io/tekton: rag-a1732009339035 
    backstage.io/kubernetes-id: rag-a1732009339035 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: jrichter/rage
  tags: ["ai", "llamacpp", "vllm", "python", "rag", "database"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 